name: Set up OCaml
description: Set up an OCaml and opam environment and add to PATH
author: Sora Morimoto <sora@morimoto.io>
branding:
  icon: package
  color: orange
inputs:
  ocaml-version:
    description: The version of the OCaml compiler to initialise
    default: latest
  opam-repository:
    description: The URL of the repository to fetch packages from
  github-token:
    description:
      The token of GitHub to authenticate on behalf of the GitHub App installed
      on your repository
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
