name: Set up OCaml
description: Set up an OCaml and opam environment and add to PATH
author: Sora Morimoto <sora@morimoto.io>
branding:
  icon: package
  color: orange
inputs:
  ocaml-version:
    description: Version of the OCaml compiler to initialise
    default: 4.11.1
  opam-repository:
    description: URL of the repository to fetch packages from
  github-token:
    description: Input for internal use; is not intended to be set by users
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
